### ISSUE TITLE
phpbench missing

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-token/jwt-framework#147]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Version              | 1.2.3

It does not appear that the `phpbench` library is actually installed, so it's not possible to run the benchmarks. Adding it to the `require-dev` gets it working fine.

**Comment by Spomky** [comment]
Actually this is not a bug but the desired behaviour.
The tools testing tools are not part of the composer.json file anymore (phpbench, phpstan, phpunit, php-cs-fixer…).
The problem is that all these tools created conflicts because of their own dependencies.
I think I will add at least phpunit in the next releases. Other tools should be install globally or using their PHAR archive.

**Comment by moderndeveloperllc** [comment]
GTK. I guess the docs for that page should be updated to mention that? Thanks for the reply and including `phpbench` configurations. I was able to figure out that EdDSA was only slightly slower than HS512 on my machine, so I'm going to give that a try instead!
