### ISSUE TITLE
google/wycheproof test vectors integration

### ISSUE THREAD

**Issue by Spomky** [web-token/jwt-framework#155]
See https://github.com/google/wycheproof

This repository contains a lot of test vectors to verify the cypher algorithms are correctly implemented.
These tests should be added to this project to detect any potential security issue.

**Comment by Spomky** [comment]
Hi @mdeboer,

That is what I would like to do. Thank you for the help.
I have some minor remarks (`\mb_strlen($test['key']) * 4` could be removed in favor of the [keySize parameter](https://github.com/google/wycheproof/blob/master/testvectors/aes_gcm_test.json#L13) or `case '128':`=>`case 128:`), but this type of test is exactly what I planned to write.

The tests marked as `acceptable` should also be managed. There should be no error whatever the results. But if the test succeeded, it should be shown somehow.

**Comment by mdeboer** [comment]
Yeah, that needs to be fixed in the Data Provider (added to the test object) as it's only available in the group object. However I wanted to return all tests instead of all groups to get a much better view which tests fail and which tests work. If it returned groups you'd only know which groups fail or succeed.

However it's a small adjustment that can be easily made and I agree it should be done. This was just quick and dirty.

The `acceptable` tests should be managed but I'm not sure how. I looked into giving a warning but PHPunit is configured to convert all warnings to exceptions. So either we need to disable this behaviour and throw a warning (and adjust the try/catch) or we need to find some other way around this. I'll have a look, suggestions are more than welcome.

Would you be okay with it if I create a feature branch and try to implement this? This is milestoned for v2 but now at least AES-GCM is correctly implemented in v1, I guess it would be no extra effort to add this to v1 and merge this in v2.

Best is probably if I create a PR and grant you access to make edits right?

Let me know, love your project 👍

**Comment by Spomky** [comment]
I agree with you, we can start a new branch and integrate these tests. Algorithms haven’t changed in v2 (or just a bit). Moreover the v1 is still maintained so this should be done in v1 first and then adapted with no effort for v2.

I am experimenting some phpunit extensions (inspired by the Symfony bridge used to catch deprecated features):

* An error is triggered from the test (e.g. `E_USER_NOTICE`)
* The errors are catched and gathered by a custom error handler in a PhpUnit listener
* Gathered errors are showed by a test runner at the end of the tests
