### ISSUE TITLE
Add documentation for GZip compression.

### ISSUE THREAD

**Issue by DavidSporer** [web-token/jwt-framework#254]
Hi,

the documentation mentions that the framework supports GZip compression but it doesn't mention how to enable it: https://web-token.spomky-labs.com/v/v1.x/#supported-compression-methods.
I hoped that there would be a GZ class or something similar to the Deflate class but there isn't such thing.
Could you please explain how to use GZip compression when creating JWEs?

Thanks,
David

**Comment by Spomky** [comment]
Hi @DavidSporer,

Non-standard compression methods have been removed since v2.x.
However, it is quite easy to add it again for your project. The compression method needs to implement `Jose\Component\Encryption\Compression\CompressionMethod`.

You can copy/paste [the deprecated class](https://github.com/web-token/jwt-framework/blob/v1.3.10/src/Component/Encryption/Compression/GZip.php) and adapt it to your project.
When done, it just has to be injected in the dedicated manager and the token header parameter `zip` set to your compression method name ([see this page](https://web-token.spomky-labs.com/v/v2.x/the-components/encrypted-tokens-jwe/jwe-creation)).

**Comment by DavidSporer** [comment]
Wow, @Spomky - thanks for that blazing-fast response :-)
Much appreciated! Keep up the great work (Huawei seems to be using GZip compression so it's still needed...).
