### ISSUE TITLE
Is there a way to create JWK Key Set from public certificate and private key ?

### ISSUE THREAD

**Issue by muditsunarctech** [web-token/jwt-framework#320]
I've been trying to generate JWK Key Set using public.cer and private.pem, but did not understand if it's possible using this package or not!

**Comment by Spomky** [comment]
Hi @muditgulgulia,

Yes it is possible. Have you read about the `JWKFatory` methods [listed in the documentation](https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset/key-management#create-key-from-external-sources) ?

**Comment by muditsunarctech** [comment]
But it don't give **alg** or **crv** used to generate the KEY

**Comment by muditsunarctech** [comment]
or is it possible to create the private key from JSON KEY Object?

**Comment by Spomky** [comment]
>But it don't give alg or crv used to generate the KEY

If the key is an EC one, the `crv` parameter will be set.
The `alg` parameter is never set because the factory cannot guess the purpose of the key. You have to set other parameters manually depending on the use case. See the example in https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset/key-management#octet-string

> or is it possible to create the private key from JSON KEY Object?

It is possible to use the [Component/Core/Util/ECKey.ph](https://github.com/web-token/jwt-framework/blob/v2.2/src/Component/Core/Util/ECKey.php) or [Component/Core/Util/RSAKey.ph](https://github.com/web-token/jwt-framework/blob/v2.2/src/Component/Core/Util/RSAKey.php) methods, but these class are marked as `internal` and may change without prior deprecation notice.

**Comment by muditsunarctech** [comment]
Thanks @Spomky  for the quick reply, you can close this because it was just a question!
