### ISSUE TITLE
Upgrade documentation for v3 missing

### ISSUE THREAD

**Issue by joostdebruijn** [web-token/jwt-framework#335]
**Version(s) affected**: 3.0.0 and above

**Description**
There is no documentation about the breaking changes between v2.0 and v3.0. Howevert, it looks like there are breaking changes (besides the major version change), because the jwt-easy package seems no longer available in v3.0.

**How to reproduce**
Search for upgrade documentation or release notes for v3.0 in the repo, Github-releases or the documentation website. It seems they are nowhere to be found.

**Possible Solution**
Write documentation about the breaking changes between v2.0 and v3.0.

**Additional context**
`composer outdated` is informing me about the release of v3.0 for jwt-framework related packages.

**Comment by Spomky** [comment]
Hi @joostdebruijn,

I finally issued [the documentation](https://web-token.spomky-labs.com/). In fact, there are not many changes between v2.x and 3.0 because it is mainly an upgrade from the deprecated version of PHP to PHP8.1

But you are right about the Easy component. It became a nightmare to manage and I received cases where users were using it incorrectly and providing the possibility of attacks.
I preferred to terminate this component and look for a better alternative.

**Comment by stof** [comment]
@Spomky the github release notes are missing for the 3.0 releases. github releases are still showing 2.2.11 as the latest release

**Comment by Spomky** [comment]
Hi @stof, this should be ok now.
