### ISSUE TITLE
web-token/jwt-experimental not on packagist

### ISSUE THREAD

**Issue by danielburger1337** [web-token/jwt-framework#528]
### Version(s) affected

3.3.0

### Description

Is it intentional that the new `web-token/jwt-experimental` package is not yet on packagist?

### How to reproduce

 ```sh
composer require web-token/jwt-experimental

In PackageDiscoveryTrait.php line 376:
                                                                                                                                             
  Could not find a matching version of package web-token/jwt-experimental. Check the package spelling, your version constraint and that the  
   package is available in a stability which matches your minimum-stability (stable).
```

**Comment by danielburger1337** [comment]
Also, in #480 you mention that `none` should stay its own package (which I agree with) but it is included in `web-token/jwt-library`. 

I think that is another error because you released `web-token/jwt-signature-none` v3.3 an hour ago and it is not a "dummy" package like the others. It actually contains the implementation.

**Comment by Spomky** [comment]
I took a long time for this version, but forgot the most basic task 😅.
This should be fixed now.

For the `none` algorithm, I revised my opinion. There is no risk because you need to explicitly instantiate/declare the algorithm AND you need to have a key of type `none` to use it effectively. This package will be marked as deprecated too.
[It is empty](https://github.com/web-token/jwt-signature-algorithm-none/tree/3.3.0) and refers to [the library package](https://github.com/web-token/jwt-signature-algorithm-none/blob/3.3.x/composer.json#L37).

**Comment by danielburger1337** [comment]
Ah, I found out why it showed me that the `none` package still has an implementation. I followed the repository link on [packagist](https://packagist.org/packages/web-token/jwt-signature-algorithm-none) which on GitHub automatically opens the `v3.0` branch instead of the latest. 

Ok, I think this is good to close. Thank you for your work!
