### ISSUE TITLE
Move `symfony/console` to the bundle

### ISSUE THREAD

**Issue by Cyperghost** [web-token/jwt-framework#533]
### Description

For non-Symfony applications, it would not be practical to have the `symfony/console` package.
The classes from the [Jose\Component\Console](https://github.com/web-token/jwt-framework/tree/4.0.x/src/Library/Console) can be moved to the [Jose\Bundle\JoseFramework\Console](https://github.com/web-token/jwt-framework/tree/4.0.x/src/Bundle). So all the Symonfy features are in one place.

**Comment by Spomky** [comment]
Hi,

The console commands can be used as standalone commands (e.g. the [JWT App](https://github.com/web-token/jwt-app)). 
That's why these classes will stay here.
The dependencies won't move in the major 3.x branches, but this will be the case in 4.x. The minor version 3.3 is a bit special as it should not break existing application but it is the only way to move to 4.x. You should restrict 3.2.x and wait for 4.0 to resollve this issue.

**Comment by Spomky** [comment]
Closing as not relevant anymore with 4.x
